//
//  UILabel+Night.h
//  UILabel+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "NSObject+Night.h"

@interface UILabel (Night)

@property (nonatomic, copy, setter = dk_setTextColorPicker:) DKColorPicker dk_textColorPicker;
@property (nonatomic, copy, setter = dk_setShadowColorPicker:) DKColorPicker dk_shadowColorPicker;
@property (nonatomic, copy, setter = dk_setHighlightedTextColorPicker:) DKColorPicker dk_highlightedTextColorPicker;

@end

@interface UILabel (Inspectable)

@property (nonatomic, strong) IBInspectable UIColor *normalTextColor;
@property (nonatomic, strong) IBInspectable UIColor *normalShadowColor;
@property (nonatomic, strong) IBInspectable UIColor *normalHighlightedTextColor;

@property (nonatomic, strong) IBInspectable UIColor *nightTextColor;
@property (nonatomic, strong) IBInspectable UIColor *nightShadowColor;
@property (nonatomic, strong) IBInspectable UIColor *nightHighlightedTextColor;

@end
