//
//  UIPageControl+Night.m
//  UIPageControl+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UIPageControl+Night.h"
#import "DKNightVersionManager.h"
#import <objc/runtime.h>

@interface UIPageControl ()

@property (nonatomic, strong) NSMutableDictionary<NSString *, DKColorPicker> *pickers;

@end

@implementation UIPageControl (Night)


- (DKColorPicker)dk_pageIndicatorTintColorPicker {
    return objc_getAssociatedObject(self, @selector(dk_pageIndicatorTintColorPicker));
}

- (void)dk_setPageIndicatorTintColorPicker:(DKColorPicker)picker {
    objc_setAssociatedObject(self, @selector(dk_pageIndicatorTintColorPicker), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    self.pageIndicatorTintColor = picker(self.dk_manager.themeVersion);
    [self.pickers setValue:[picker copy] forKey:@"setPageIndicatorTintColor:"];
}

- (DKColorPicker)dk_currentPageIndicatorTintColorPicker {
    return objc_getAssociatedObject(self, @selector(dk_currentPageIndicatorTintColorPicker));
}

- (void)dk_setCurrentPageIndicatorTintColorPicker:(DKColorPicker)picker {
    objc_setAssociatedObject(self, @selector(dk_currentPageIndicatorTintColorPicker), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    self.currentPageIndicatorTintColor = picker(self.dk_manager.themeVersion);
    [self.pickers setValue:[picker copy] forKey:@"setCurrentPageIndicatorTintColor:"];
}


@end

@implementation UIPageControl (Inspectable)

- (UIColor *)normalPageIndicatorTintColor {
    return objc_getAssociatedObject(self, @selector(normalPageIndicatorTintColor));
}

- (void)setNormalPageIndicatorTintColor:(UIColor *)normalPageIndicatorTintColor {
    objc_setAssociatedObject(self, @selector(normalPageIndicatorTintColor), normalPageIndicatorTintColor, OBJC_ASSOCIATION_COPY_NONATOMIC);
}

- (UIColor *)normalCurrentPageIndicatorTintColor {
    return objc_getAssociatedObject(self, @selector(normalCurrentPageIndicatorTintColor));
}

- (void)setNormalCurrentPageIndicatorTintColor:(UIColor *)normalCurrentPageIndicatorTintColor {
    objc_setAssociatedObject(self, @selector(normalCurrentPageIndicatorTintColor), normalCurrentPageIndicatorTintColor, OBJC_ASSOCIATION_COPY_NONATOMIC);
}


- (UIColor *)nightPageIndicatorTintColor {
    return objc_getAssociatedObject(self, @selector(nightPageIndicatorTintColor));
}

- (void)setNightPageIndicatorTintColor:(UIColor *)nightPageIndicatorTintColor {
    objc_setAssociatedObject(self, @selector(nightPageIndicatorTintColor), nightPageIndicatorTintColor, OBJC_ASSOCIATION_COPY_NONATOMIC);
}

- (UIColor *)nightCurrentPageIndicatorTintColor {
    return objc_getAssociatedObject(self, @selector(nightCurrentPageIndicatorTintColor));
}

- (void)setNightCurrentPageIndicatorTintColor:(UIColor *)nightCurrentPageIndicatorTintColor {
    objc_setAssociatedObject(self, @selector(nightCurrentPageIndicatorTintColor), nightCurrentPageIndicatorTintColor, OBJC_ASSOCIATION_COPY_NONATOMIC);
}

@end
