//
//  UISlider+Night.h
//  UISlider+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "NSObject+Night.h"

@interface UISlider (Night)

@property (nonatomic, copy, setter = dk_setMinimumTrackTintColorPicker:) DKColorPicker dk_minimumTrackTintColorPicker;
@property (nonatomic, copy, setter = dk_setMaximumTrackTintColorPicker:) DKColorPicker dk_maximumTrackTintColorPicker;
@property (nonatomic, copy, setter = dk_setThumbTintColorPicker:) DKColorPicker dk_thumbTintColorPicker;

@end

@interface UISlider (Inspectable)

@property (nonatomic, strong) IBInspectable UIColor *normalMinimumTrackTintColor;
@property (nonatomic, strong) IBInspectable UIColor *normalMaximumTrackTintColor;
@property (nonatomic, strong) IBInspectable UIColor *normalThumbTintColor;

@property (nonatomic, strong) IBInspectable UIColor *nightMinimumTrackTintColor;
@property (nonatomic, strong) IBInspectable UIColor *nightMaximumTrackTintColor;
@property (nonatomic, strong) IBInspectable UIColor *nightThumbTintColor;

@end
