//
//  UIProgressView+Night.h
//  UIProgressView+Night
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "NSObject+Night.h"

@interface UIProgressView (Night)

@property (nonatomic, copy, setter = dk_setProgressTintColorPicker:) NNColorPicker dk_progressTintColorPicker;
@property (nonatomic, copy, setter = dk_setTrackTintColorPicker:) NNColorPicker dk_trackTintColorPicker;

@end
